# References
# Overall: https://cran.r-project.org/web/packages/renv/vignettes/docker.html
# Handling local sources: https://rstudio.github.io/renv/articles/local-sources.html
# Ignoring dev dependencies: https://rstudio.github.io/renv/articles/faq.html

# Environment variables
ENV R_PACKAGE_VERSION $(cat .docker_env_package_version;
ENV R_VERSION $(cat .docker_env_r_version;

FROM rocker/r-ver:${R_VERSION}

LABEL version=${R_PACKAGE_VERSION}
LABEL maintainer='Janko Thyson &lt;janko.thyson@rappster.io&gt; [aut, cre]'

RUN echo "Package repository"
RUN R -e 'getOption("repos")'
RUN R -e 'options("repos" = "https://packagemanager.rstudio.com/all/__linux__/focal/latest")'
RUN R -e 'getOption("repos")'
#RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "install.packages('remotes')"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"

# Copy required components for cache management ----------
WORKDIR /dep_manager
COPY renv.lock renv.lock

# Install Linux libs ----------
#RUN apt-get update && apt-get install -y libsasl2-dev libssl-dev libcurl4 libcurl4-openssl-dev libxml2-dev libsodium-dev
#RUN apt-get update && apt-get dist-upgrade -y --force-yes && apt-get autoremove && apt-get autoclean && apt-get install -y --force-yes -f libsasl2-dev libssl-dev libcurl4 libcurl4-openssl-dev libxml2-dev libsodium-dev
RUN apt-get update && \
  apt-get autoremove && \
  apt-get autoclean && \
  apt-get install \
  -y \
  --force-yes \
  -f libsasl2-dev \
  libssl-dev \
  libcurl4 \
  libcurl4-openssl-dev \
  libxml2-dev \
  libsodium-dev \
  libgit2-dev \
  zlib1g-dev \
  libz-dev

# Restore dependencies ----------
RUN R -e 'renv::consent(provided = TRUE)'

# Build actual cache files ----------
CMD R --no-save -e 'renv::activate()' -e 'renv::restore()'
